apiVersion: apps/v1
kind: Deployment
metadata:
  name: snooker-club-api
  namespace: snooker-club
  labels:
    app: snooker-club-api
    release: snooker-club-api
spec:
  selector:
    matchLabels:
      app: snooker-club-api
      release: snooker-club-api
      tier: backend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: snooker-club-api
        release: snooker-club-api
        tier: backend
    spec:
      imagePullSecrets:
        - name: dockerconfig
      containers:
        - image: registry.gitlab.com/steffbeckers/snooker-club/api
          name: snooker-club-api
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #     initialDelaySeconds: 5
          #     periodSeconds: 5
          #     successThreshold: 1
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: snooker-club-api
  namespace: snooker-club
  labels:
    app: snooker-club-api
    release: snooker-club-api
spec:
  ports:
    - port: 80
  selector:
    app: snooker-club-api
    release: snooker-club-api
    tier: backend
